### ISSUE TITLE
Too many open files  - persistent storage and  SXXP0003: Error reported by XML parser

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#108]
Got this error when performing the WMS 1.3 client test with TE 4.1 in a Linux Box

Console log:

```

SEVERE: IOException while saving persisted sessions: java.io.FileNotFoundException: /srv/srv/teamengine-prod-20150619/work/Catalina/localhost/teamengine/SESSIONS.ser (Too many open files)
java.io.FileNotFoundException: /srv/srv/teamengine-prod-20150619/work/Catalina/localhost/teamengine/SESSIONS.ser (Too many open files)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
	at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:386)
	at org.apache.catalina.session.StandardManager.unload(StandardManager.java:353)
	at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:518)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5622)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3947)
	at org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:426)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1345)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1530)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1519)
	at java.lang.Thread.run(Thread.java:745)

Jun 23, 2015 1:32:46 PM org.apache.catalina.session.StandardManager stopInternal
SEVERE: Exception unloading sessions to persistent storage
java.io.FileNotFoundException: /srv/srv/teamengine-prod-20150619/work/Catalina/localhost/teamengine/SESSIONS.ser (Too many open files)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
	at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:386)
	at org.apache.catalina.session.StandardManager.unload(StandardManager.java:353)
	at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:518)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5622)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3947)
	at org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:426)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1345)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1530)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1519)
	at java.lang.Thread.run(Thread.java:745)

Jun 23, 2015 1:32:46 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/teamengine] appears to have started a thread named [Thread-4] but has failed to stop it. This is very likely to create a memory leak.
Jun 23, 2015 1:32:47 PM org.apache.catalina.startup.ContextConfig getWebXmlSource
SEVERE: Error processed default web.xml named conf/web.xml at /srv/local/teamengine-prod/conf/web.xml
java.io.FileNotFoundException: /srv/local/teamengine-prod/conf/web.xml (Too many open files)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.apache.catalina.startup.ContextConfig.getWebXmlSource(ContextConfig.java:1847)
	at org.apache.catalina.startup.ContextConfig.getGlobalWebXmlSource(ContextConfig.java:1754)
	at org.apache.catalina.startup.ContextConfig.getDefaultWebXmlFragment(ContextConfig.java:1411)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1246)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:878)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:376)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3954)
	at org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:426)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1345)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1530)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1519)
	at java.lang.Thread.run(Thread.java:745)

Jun 23, 2015 1:32:47 PM org.apache.catalina.core.ApplicationContext log
SEVERE: Failed to locate resource [/WEB-INF/web.xml] in context [/teamengine]
java.io.FileNotFoundException: /srv/srv/teamengine-prod-20150619/webapps/teamengine/WEB-INF/web.xml (Too many open files)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.apache.naming.resources.FileDirContext$FileResource.streamContent(FileDirContext.java:900)
	at org.apache.catalina.core.ApplicationContext.getResourceAsStream(ApplicationContext.java:581)
	at org.apache.catalina.core.ApplicationContextFacade.getResourceAsStream(ApplicationContextFacade.java:212)
	at org.apache.catalina.startup.ContextConfig.getContextWebXmlSource(ContextConfig.java:1798)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1251)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:878)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:376)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3954)
	at org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:426)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1345)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1530)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1519)
	at java.lang.Thread.run(Thread.java:745)

Jun 23, 2015 1:32:47 PM org.apache.naming.resources.FileDirContext list
WARNING: Could not get dir listing for /srv/srv/teamengine-prod-20150619/webapps/teamengine/WEB-INF/lib
Jun 23, 2015 1:32:47 PM org.apache.naming.resources.FileDirContext list
WARNING: Could not get dir listing for /srv/srv/teamengine-prod-20150619/webapps/teamengine/WEB-INF/classes
Jun 23, 2015 1:32:47 PM org.apache.catalina.core.StandardContext reload
INFO: Reloading Context with name [/teamengine] is completed
Jun 23, 2015 1:34:20 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/teamengine] threw exception [java.lang.NullPointerException] with root cause
java.lang.NullPointerException


```

**Comment by bermud** [comment]
Richard responded:
You can use the lsof command to see what’s opening so many files.

<http://www.tecmint.com/10-lsof-command-examples-in-linux/>

 If necessary you can increase the allowed number of open files (how this is done depends on the Linux distribution).

**Comment by bermud** [comment]
We increased the number of open files for tomcat from 1024 to 2048.
