### ISSUE TITLE
 Null pointer issue for wms 1.1.1 and wms 1.3.0 on teamengine. 

### ISSUE THREAD

**Issue by DineshDhyani** [opengeospatial/teamengine#115]
I am facing below issue for wms 1.1.1 and wms 1.3.0 for teamengine. When I  tried to setup locally 
engine build fails for :: 
 TEAM Engine - Core Module .......................... FAILURE [  4.730 s]
 TEAM Engine - Service Providers .................... SKIPPED
 TEAM Engine - Web Application ...................... SKIPPED
 TEAM Engine - Console Application .................. SKIPPED
 
Is anyone else facing this or am i missing something?

Thanks in advance.

Logs::

Test Name : wms:wms_main type Mandatory
net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.NullPointerException
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:192)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:567)
	at com.occamlab.te.TECore.executeTest(TECore.java:775)
	at com.occamlab.te.TECore.execute_test(TECore.java:386)
	at com.occamlab.te.TECore.execute_suite(TECore.java:434)
	at com.occamlab.te.TECore.execute(TECore.java:291)
	at com.occamlab.te.Test.execute(Test.java:314)
	at com.occamlab.te.Test.main(Test.java:90)
Caused by: net.sf.saxon.trans.XPathException: Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.NullPointerException
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:151)
	at net.sf.saxon.expr.PathExpression.iterate(PathExpression.java:848)
	at net.sf.saxon.sort.DocumentSorter.iterate(DocumentSorter.java:84)
	at net.sf.saxon.instruct.CopyOf.processLeavingTail(CopyOf.java:292)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
	at net.sf.saxon.instruct.DocumentInstr.evaluateItem(DocumentInstr.java:282)
	at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:295)
	at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:341)
	at net.sf.saxon.expr.LetExpression.process(LetExpression.java:372)
	at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
	at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
	at net.sf.saxon.Controller.transform(Controller.java:1560)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
	... 7 more
Caused by: java.lang.NullPointerException
	at com.occamlab.te.TECore.parse(TECore.java:1946)
	at com.occamlab.te.TECore.parse(TECore.java:1923)
	at com.occamlab.te.TECore.request(TECore.java:1523)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
	at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
	... 22 more

**Comment by bermud** [comment]
@DineshDhyani, sorry to get you this late. Which version of TEAM Engine are you building, master? Are you building doing 'mvn clean install'?

**Comment by bermud** [comment]
@DineshDhyani, Im closing this issue. Let us know if you still have problems.
