### ISSUE TITLE
Application throws a Java error when validating a KML file

### ISSUE THREAD

**Issue by CLEAOSBORNE** [opengeospatial/teamengine#162]
Web page launches with numerous available Test Suites, however seems to have issues when running KML validation tests.  Application throws a java error........see log file below.  Any help would be greatly appreciated.

Thanks

2016/04/05-12:08:15 ERROR
Test Name : tns:Main type Mandatory
net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function java.lang.Exception: Fatal Error: XPath syntax error at char 19 on line 47 in {tng:new($outputDir)}:
    Cannot find a matching 1-argument function named {java:org.opengis.cite.kml22.TestNGController}new(); SystemID: file:/c:/TE_BASE/work/_TE_BASE_scripts_kml22_2.2_ctl_/kml22-suite/tns$run-ets-kml22.fn; Line#: 47; Column#: -1
Fatal Error: XPath syntax error at char 40 on line 50 in {...Run($controller, $testRunAr...}:
    Cannot find a matching 2-argument function named {java:org.opengis.cite.kml22.TestNGController}doTestRun(); SystemID: file:/c:/TE_BASE/work/_TE_BASE_scripts_kml22_2.2_ctl_/kml22-suite/tns$run-ets-kml22.fn; Line#: 50; Column#: -1
Failed to compile stylesheet. 2 errors detected.
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:192)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:571)
	at com.occamlab.te.TECore.executeTest(TECore.java:782)
	at com.occamlab.te.TECore.execute_test(TECore.java:390)
	at com.occamlab.te.TECore.execute_suite(TECore.java:438)
	at com.occamlab.te.TECore.execute(TECore.java:295)
	at com.occamlab.te.TECore.run(TECore.java:2276)
	at java.lang.Thread.run(Unknown Source)
Caused by: net.sf.saxon.trans.XPathException: Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function java.lang.Exception: Fatal Error: XPath syntax error at char 19 on line 47 in {tng:new($outputDir)}:
    Cannot find a matching 1-argument function named {java:org.opengis.cite.kml22.TestNGController}new(); SystemID: file:/c:/TE_BASE/work/_TE_BASE_scripts_kml22_2.2_ctl_/kml22-suite/tns$run-ets-kml22.fn; Line#: 47; Column#: -1
Fatal Error: XPath syntax error at char 40 on line 50 in {...Run($controller, $testRunAr...}:
    Cannot find a matching 2-argument function named {java:org.opengis.cite.kml22.TestNGController}doTestRun(); SystemID: file:/c:/TE_BASE/work/_TE_BASE_scripts_kml22_2.2_ctl_/kml22-suite/tns$run-ets-kml22.fn; Line#: 50; Column#: -1
Failed to compile stylesheet. 2 errors detected.
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:151)
	at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:352)
	at net.sf.saxon.expr.Expression.process(Expression.java:461)
	at net.sf.saxon.instruct.DocumentInstr.evaluateItem(DocumentInstr.java:282)
	at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:295)
	at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:341)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:542)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
	at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
	at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
	at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
	at net.sf.saxon.Controller.transform(Controller.java:1560)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
	... 7 more
Caused by: java.lang.Exception: Fatal Error: XPath syntax error at char 19 on line 47 in {tng:new($outputDir)}:
    Cannot find a matching 1-argument function named {java:org.opengis.cite.kml22.TestNGController}new(); SystemID: file:/c:/TE_BASE/work/_TE_BASE_scripts_kml22_2.2_ctl_/kml22-suite/tns$run-ets-kml22.fn; Line#: 47; Column#: -1
Fatal Error: XPath syntax error at char 40 on line 50 in {...Run($controller, $testRunAr...}:
    Cannot find a matching 2-argument function named {java:org.opengis.cite.kml22.TestNGController}doTestRun(); SystemID: file:/c:/TE_BASE/work/_TE_BASE_scripts_kml22_2.2_ctl_/kml22-suite/tns$run-ets-kml22.fn; Line#: 50; Column#: -1
Failed to compile stylesheet. 2 errors detected.
	at com.occamlab.te.Engine.loadExecutable(Engine.java:190)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:552)
	at com.occamlab.te.TECore.executeXSLFunction(TECore.java:1037)
	at com.occamlab.te.TECore.callFunction(TECore.java:1069)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
	at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
	... 30 more
Caused by: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 2 errors detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
	at net.sf.saxon.PreparedStylesheet.compile(PreparedStylesheet.java:79)
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:146)
	at com.occamlab.te.Engine.loadExecutable(Engine.java:181)
	... 40 more

**Comment by bermud** [comment]
Thank you for reporting. We will investigate.

**Comment by CLEAOSBORNE** [comment]
@bermud  - Thanks Bermud, I managed to fix the java error and the application is working as intended.

**Comment by bermud** [comment]
@CLEAOSBORNE , Great! Thank you for letting us know.

**Comment by Vinni0803** [comment]
@CLEAOSBORNE , I'm facing same type of issue  https://github.com/opengeospatial/ets-wfs11/issues/53
Any help would be appreciated.

**Comment by CLEAOSBORNE** [comment]
@Vinni0803 What worked for me was re-running mvn package -P ogc.cite -Dets-resources-version=YY.MM.DD    

find out what version of ets-resources you have and place it in the above command for YY.MM.DD

Then rebuild the war file.

**Comment by Vinni0803** [comment]
How can i find  the version of ets-resources??

**Comment by CLEAOSBORNE** [comment]
@Vinni0803 Did you perform a Windows or Linux install?  Check out this link :  http://opengeospatial.github.io/teamengine/installation.html

It speaks on configuring the ogc settings

**Comment by Vinni0803** [comment]
@CLEAOSBORNE  Windows installation 
Did everything as mentioned in above link, still same issue.

**Comment by CLEAOSBORNE** [comment]
@Vinni0803 I would try running that setup_base script in ets-resources with the CTL CSV file and rebuild the war file
