### ISSUE TITLE
Root cause exception is not logged when XMLValidatingParser fails

### ISSUE THREAD

**Issue by dgtombs** [opengeospatial/teamengine#359]
TEAM Engine v5.3.

If XMLValidatingParser.parse() parsing fails for some reason, the root cause exception is lost.

### Steps to reproduce:

1. Make TEAM Engine unable to look up a WCS-related schema for some reason. (If you switch your nameserver to rns1.earthlink.net, w3.org will not resolve--that is how I found this issue.)
2. Run the WCS test suite.

### Expected result:

`session_dir/error_log/log.txt` contains the actual root cause exception, like:

    Caused by: org.xml.sax.SAXParseException; systemId: http://schemas.opengis.net/ows/2.0/owsCommon.xsd; lineNumber: 76; columnNumber: 45; src-resolve: Cannot resolve the name 'xlink:simpleAttrs' to a(n) 'attribute group' component.
             at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
             etc...

### Actual result:

The lowest-level exception recorded in `session_dir/error_log/log.txt` is:

    Caused by: java.lang.RuntimeException: Failed to parse resource from http://ows.eox.at/cite/mapserver?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities
     src-resolve: Cannot resolve the name 'xlink:simpleAttrs' to a(n) 'attribute group' component.
            at com.occamlab.te.parsers.XMLValidatingParser.parse(XMLValidatingParser.java:227)
            ... 60 more

This provides very little information as to what the actual problem is. In fact, it is confusing because it sounds like a problem with `http://ows.eox.at/cite/mapserver?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities`, which is not the case.

**Comment by dstenger** [comment]
@keshav-nangare Can you please test/verify the pull request?
