### ISSUE TITLE
Session not starts properly in TE web service

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#38]
## Session not starts properly when:
 - user start a test
 - the form doesn't shows. Wheel spins forever.
 - And the user stops the process

##  Console error
Jun 19, 2014 11:12:32 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [test] in context with path [/teamengine] threw exception [java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at com.occamlab.te.web.TestServlet.process(TestServlet.java:293)
	at com.occamlab.te.web.TestServlet.doGet(TestServlet.java:192)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

-------

## Error thrown to user

HTTP Status 500 - java.io.FileNotFoundException: /home/bitnami/TE_BASE/users/ogctest/undefined/session.xml (No such file or directory)

type Exception report

message java.io.FileNotFoundException: /home/bitnami/TE_BASE/users/ogctest/undefined/session.xml (No such file or directory)

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: java.io.FileNotFoundException: /home/bitnami/TE_BASE/users/ogctest/undefined/session.xml (No such file or directory)
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:549)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:460)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

java.io.FileNotFoundException: /home/bitnami/TE_BASE/users/ogctest/undefined/session.xml (No such file or directory)
	java.io.FileInputStream.open(Native Method)
	java.io.FileInputStream.<init>(Unknown Source)
	java.io.FileInputStream.<init>(Unknown Source)
	sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
	sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source)
	org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	com.occamlab.te.web.TestSession.load(TestSession.java:77)
	org.apache.jsp.viewSessionLog_jsp._jspService(viewSessionLog_jsp.java:209)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.53 logs.

**Comment by bermud** [comment]
It occurs, when I add a description for a test session, don't leave the form field and start the test.
Please investigate further.

**Comment by bermud** [comment]
@upendra-sachan  I have been able to replicate the issue as describe above. Please fix.
